### ISSUE TITLE
New release for Scala 2.13 with newer scalac-scoverage-plugin version?

### ISSUE THREAD

**Issue by andreisilviudragnea** [scoverage/scoverage-maven-plugin#100]

**Comment by gslowikowski** [comment]
Version `1.4.11` supports Scala 2.13.

**Comment by RPCMoritz** [comment]
Sadly not 2.13.9 and 2.13.10 which include security fixes over 2.13.8

**Comment by jozic** [comment]
At my company we use latest scoverage with Scala 2.13.10. No issues.

**Comment by RPCMoritz** [comment]
And you trigger it with the latest version of this maven plugin?
There are [no supporting releases](https://mvnrepository.com/artifact/org.scoverage/scalac-scoverage-plugin_2.13.8/1.4.11) that I can see - unless the plugin moves to the scoverage-2.0 API, with the above linked PR.

**Comment by rahulsinghai** [comment]
This issue can be marked resolved, as version `1.4.11` supports Scala `2.13`.

**Comment by jozic** [comment]
As mentioned above, latest plugin version works fine with the latest Scala 2.13 (which is 2.13.12 atm). Please reopen with more details if you experience any issues.
