### ISSUE TITLE
New release for scoverage 2.x and Scala 3.x

### ISSUE THREAD

**Issue by jozic** [scoverage/scoverage-maven-plugin#106]
Any plans to update maven plugin to support latest and greatest [scalac-scoverage-plugin](https://github.com/scoverage/scalac-scoverage-plugin)?

@ckipp01, where one should look to help with this?

**Comment by ckipp01** [comment]
> Any plans to update maven plugin to support latest and greatest [scalac-scoverage-plugin](https://github.com/scoverage/scalac-scoverage-plugin)?

No plans from me as I don't use Maven at all. So it'll have to come from the community.

> @ckipp01, where one should look to help with this?

You can see the bulk of the changes outlined [here](https://github.com/scoverage/scalac-scoverage-plugin/releases/tag/v2.0.0-M2) in the release notes. I'd also recommend taking a look at the other integrations, like the [sbt-plugin](https://github.com/scoverage/sbt-scoverage/blob/main/src/main/scala/scoverage/ScoverageSbtPlugin.scala) to see how it handles the new version and also Scala 3.

**Comment by jozic** [comment]
fixed by #107, #143, #149
