### ISSUE TITLE
how to switch between statement or branch coverage as default

### ISSUE THREAD

**Issue by arcsoftech** [scoverage/scoverage-maven-plugin#109]
I can see this changes are made to sbt-coverage plugin but no change has been done to this plugin.
[issue in sbt coverage](https://github.com/scoverage/sbt-scoverage/issues/221)

I want to set different minimum coverage of statement and branch. Right now only statement coverage is considered when we set minimum coverage.

**Comment by jozic** [comment]
this should be addressed by #55

**Comment by jozic** [comment]
@arcsoftech please try version 2.0.1. 
Please report back if you have issues
