### ISSUE TITLE
maven-scala-plugin not supported

### ISSUE THREAD

**Issue by goal1860** [scoverage/scoverage-maven-plugin#123]
After hours of trial and err I found it will skip report generation if maven-scala plugin is used to compile scala code:
```
<plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <version>2.15.2</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
          <!--args>
            <arg>-target:jvm-1.8</arg>
          </args-->
        </configuration>
      </plugin>
```
I had to use alchim31 maven plugin to make it work:
```
<plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.2.2</version>
        <executions>
          <execution>
            <id>default-sbt-compile</id>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
Is this documented somewhere I missed or actually a bug?
I posted more details on stackoverflow:
https://stackoverflow.com/questions/75681259/scoverage-maven-plugin-does-not-generate-html-report/75682545#75682545

**Comment by jozic** [comment]
just curious, is this some kind of legacy project you were trying to add scoverage to? as the latest version of `maven-scala-plugin` is from 2011. Can it compile Scala versions supported by this plugin?

**Comment by jozic** [comment]
btw, README has this documented [here](https://github.com/scoverage/scoverage-maven-plugin#prerequisities--limitations), so I will close this. Please send a PR to update  documentation if you think it can be better. Thanks.
