### ISSUE TITLE
Handle move of Doxia from Codehaus to Apache

### ISSUE THREAD

**Issue by hunterpayne** [scoverage/scoverage-maven-plugin#139]
All Doxia classes like: org.codehaus.doxia.sink.Sink need to change to org.apache.doxia.sink.Sink in newer versions of maven.  The site plugin has changed the signature of generate that it searches for.  This causes and exception to be thrown and documents to not be generated.

**Comment by jozic** [comment]
Could you please share more details? mvn version, plugin version, java/scala, etc
ideally a small reproducible project.
Thanks

**Comment by hunterpayne** [comment]
So in version 4 of Maven, they seems to switch the Doxia classes from org.codehause to org.apache.  I think there is a bug in maven-site-plugin that jumps the gun on this change and its breaking generation of the aggregated reports (yours and another plugin).  However, I don't think the problem is with your project anymore.  I believe this problem is from the maven-site-plugin.  So I'm going to close this issue.

That being said, when Maven 4 (I think) comes out, you are going to have to make these updates for versions of your plugin that are intended to work in Maven 4.  But that's a separate issue that perhaps you were already aware of.

**Comment by hunterpayne** [comment]
Closing as I believe this bug is actually in the maven-site-plugin.  Sorry for that.
