### ISSUE TITLE
How to disable scoverage report when building via maven?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [scoverage/scoverage-maven-plugin#17]
e.g. any particular configuration of report goal?

**Comment by StarWindMoonCloud** [comment]
Example:
I can execute "mvn test" to run test as well as scoverage, but any parameter in place that I can run like "mvn test -DskipScoverage" to skip scoverage?
https://github.com/StarWindMoonCloud/scoverage-specs2-test

**Comment by gslowikowski** [comment]
`-Dscoverage.skip` (http://scoverage.github.io/scoverage-maven-plugin/1.0.4/report-mojo.html#skip), BTW you can upgrade plugin version to 1.0.4 (latest).

**Comment by StarWindMoonCloud** [comment]
Hi,
Just changed the issue, my question is more about that all the tests are run twice with -Dscoverage.skip
That's not what we what, when the pkg/test is larger, it's waisting more time, is there any smart way to avoid it?

Refer to below:
INFO] Surefire report directory: /Users/qili/git/scoverage-specs2-test/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-specs2-plugin:0.4.2:run-specs (test) @ scoverage-spec2-test ---
[INFO] com.qili.SampleTest:
test input
[INFO] Success: 1   Error: 0   Failure: 0   Skipped: 0
[INFO] com.qili.SampleObjectTest:
[INFO] Success: 1   Error: 0   Failure: 0   Skipped: 0
[INFO]
[INFO] >>> scoverage-maven-plugin:1.0.2:report (coverage) > [scoverage]test @ scoverage-spec2-test >>>
[INFO]
[INFO] --- scoverage-maven-plugin:1.0.2:pre-compile (coverage) @ scoverage-spec2-test ---
[INFO] Skipping Scoverage execution
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ scoverage-spec2-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/qili/git/scoverage-specs2-test/src/main/resources
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ scoverage-spec2-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ scoverage-spec2-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:compile (compile) @ scoverage-spec2-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scoverage-maven-plugin:1.0.2:post-compile (coverage) @ scoverage-spec2-test ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ scoverage-spec2-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/qili/git/scoverage-specs2-test/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ scoverage-spec2-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:3.2.0:testCompile (test-compile) @ scoverage-spec2-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ scoverage-spec2-test ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-specs2-plugin:0.4.2:run-specs (test) @ scoverage-spec2-test ---
[INFO] com.qili.SampleTest:
test input
[INFO] Success: 1   Error: 0   Failure: 0   Skipped: 0
[INFO] com.qili.SampleObjectTest:
[INFO] Success: 1   Error: 0   Failure: 0   Skipped: 0
[INFO]
[INFO] <<< scoverage-maven-plugin:1.0.2:report (coverage) < [scoverage]test @ scoverage-spec2-test <<<
[INFO]
[INFO] --- scoverage-maven-plugin:1.0.2:report (coverage) @ scoverage-spec2-test ---
[INFO] Skipping SCoverage report generation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.335 s
[INFO] Finished at: 2015-03-12T14:04:38-07:00
[INFO] Final Memory: 16M/369M

**Comment by gslowikowski** [comment]
Fixed and `1.0.5-SNAPSHOT` version deployed to Sonatype snapshots repository.
You need to switch to this version, add:
```xml
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```
to your project.

Test it please.

**Comment by gslowikowski** [comment]
New `1.0.5-SNAPSHOT` version deployed to Sonatype snapshots repository.

**Comment by gslowikowski** [comment]
I assume the issue has been fixed.
