### ISSUE TITLE
Add aggregated reports for multi-module projects

### ISSUE THREAD

**Issue by gslowikowski** [scoverage/scoverage-maven-plugin#19]
Add feature similar to https://github.com/scoverage/sbt-scoverage#user-content-multi-project-reports.

Instead of new mojo, 'aggregate' parameter will be added to existing reporting mojos with default value `false`. When set to `true` additional aggregated report for top-level project will be generated.

**Comment by gslowikowski** [comment]
Done. New `1.1.0-SNAPSHOT` deployed. Maven generated site updated (see http://scoverage.github.io/scoverage-maven-plugin/1.1.0-SNAPSHOT/report-mojo.html#aggregate).

**Comment by gslowikowski** [comment]
New `1.1.0-SNAPSHOT` deployed.

**Comment by gslowikowski** [comment]
New 1.1.0-SNAPSHOT deployed.

**Comment by gurmeetsaran** [comment]
@gslowikowski - eagerly waiting for this patch to be available on 1.1.0

**Comment by gslowikowski** [comment]
Implementation of this functionality is tricky because usually (when it's also a parent of its modules) root projects is executed first, but aggregated report must be generated last. Aggregated report is generated be the last reactor project for the root project. This is already implemented, but I need some more time for testing.

Can you test `1.1.0-SNAPSHOT` version? If yes, just set `aggregate` parameter to `true` (http://scoverage.github.io/scoverage-maven-plugin/1.1.0-SNAPSHOT/report-mojo.html#aggregate).

Additionally I need to add some documentation about this feature to use it effectively.
