### ISSUE TITLE
Scoverage Not genereted

### ISSUE THREAD

**Issue by jjayeshgohil** [scoverage/scoverage-maven-plugin#20]
Hi,

I am having issues with my project as scoverage is not getting generated. I have attached the log of mvn test scoverage:report -X with maven version being 3.2.5.

Can you please help with this? Please rename the file to .txt.

Thanks,

Jayesh
![scala_log](https://cloud.githubusercontent.com/assets/8721355/7595936/b07b1c60-f8af-11e4-8816-bba8a66aa68d.jpg)

**Comment by gslowikowski** [comment]
403 Forbidden
Can you send it to me directly?

**Comment by jjayeshgohil** [comment]
Please check your mail. I just sent it.

**Comment by gslowikowski** [comment]
You are using `org.scala-tools:maven-scala-plugin` version `2.15.2`.
Upgrade to `net.alchim31.maven:scala-maven-plugin`. Minimum version is `3.0.0`, latest is `3.2.0`. 

Scoverage plugin needs to set `addScalacArgs` and `analysisCacheFile` build properties in forked `scoverage` Maven lifecycle. Versions of `maven-scala-plugin` before `3.0.0` do not support these properties. 
Read https://github.com/scoverage/scoverage-maven-plugin#prerequisities--limitations.

**Comment by jjayeshgohil** [comment]
That's what it was. I am able to generate scoverage.xml. Thank you.
