### ISSUE TITLE
Plugin is not generating report

### ISSUE THREAD

**Issue by tenstriker** [scoverage/scoverage-maven-plugin#28]
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.0:integration-report (default-cli) < [scoverage]verify @ myapp-rest <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.0:integration-report (default-cli) @ myapp ---
[INFO] Skipping SCoverage report generation
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.0:report-only (default-cli) @ myapp ---
[INFO] Skipping SCoverage report generation

It keeps on skipping report generation. I tried version 1.1.1 and 1.1.0. Both exhibit same behavior. 

maven command line:
`clean -X scoverage:integration-report scoverage:report-only`

It does instrument classes. I see following directories under target dir:
scoverage-classes
scoverage-classes.timestamp
 scoverage-myapp.jar
scoverage-myapp.jar.original

but no reports directory

**Comment by gslowikowski** [comment]
`scoverage:report-only` is redundant here.

Can you attach `mvn clean scoverage:integration-report -X` execution log (or send it directly to me, if you cannot publish it)?

**Comment by tenstriker** [comment]
Not sure if I can share full detailed log. I have to check on that with my manager. but I can send specific part from logs if you direct me there. If you know possible cases I can check all of those.  In my opinion mojo should tell reason for skipping reports though.

here's pom config for reference.

`<plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.1.1</version>
                <configuration>
                    <scalaVersion>2.10.5</scalaVersion>
                    <highlighting>true</highlighting>
                    <minimumCoverage>80</minimumCoverage>
                    <failOnMinimumCoverage>false</failOnMinimumCoverage>
                    <excludes>
                        <exclude>**/com/mycom/myproj/*.java</exclude>
                    </excludes>
                    <includes>
                        <include>**/com/mycom/myproj/*.scala</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-check</goal> 
                        </goals>
                        <phase>test</phase> 
                    </execution>
                </executions>
             </plugin>`

Thanks

**Comment by gslowikowski** [comment]
Try to remove executions from `pom.xml` and check if it helps.

**Comment by gslowikowski** [comment]
What's your `scala-maven-plugin`, `maven-surefire-plugin` and `maven-failsafe-plugin`?

**Comment by tenstriker** [comment]
I presume your asking for their versions: 
`<artifactId>maven-scala-plugin</artifactId>
        <version>2.15.2</version>`

`<artifactId>maven-surefire-plugin</artifactId>
        <version>2.12</version>`

I don't have maven-failsafe-plugin in pom

**Comment by gslowikowski** [comment]
I mean configurations.
If you don't have `maven-failsafe-plugin`, how are integration tests executed?

**Comment by tenstriker** [comment]
Using spring `@IntegrationTest @WebIntegrationTest @TestExecutionListener` and extending `AbstractTestNGSpringContextTests` it runs testsng suite as a part of unit test I think

**Comment by tenstriker** [comment]
I removed execution tag from scoverage plugin. I added failsafe plugin. Looks like its running tests twice so I think I need to avoid running integration test as it's doing same thing. I also noticed following:

[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:integration-check (default) < [scoverage]verify @ insights-rest <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:integration-check (default) @ insights-rest ---
[INFO] Cannot perform check, instrumentation not performed - skipping

**Comment by gslowikowski** [comment]
I mean, how you configured integration tests execution in Maven.

Anyway, I think the reason of your problems is too old `maven-scala-plugin`. Read https://github.com/scoverage/scoverage-maven-plugin/#prerequisities--limitations.

**Comment by tenstriker** [comment]
I tried using 3.2.1 `maven-scala-plugin`. I can build it on my local system and  can see following dir being generated. 
target/scoverage-data/scoverage.coverage.xml 
Is that the one for coverage report? I can visualize it as my jenkins build is now failing with the 

However it fails on Jenkins with following error:
`[ERROR] error: scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.` But that's probably unrelated to scoverage plugin.

**Comment by gslowikowski** [comment]
`target/scoverage-data/scoverage.coverage.xml` contains information about instrumented code. Its existence means sources were instrumented. Instrumented sources are in `target/scoverage-classes` directory.

If there are no `target/scoverage-data/scoverage-measurements.nnn` files, either tests were not executed on instrumented code or tests were executed, but didn't call instrumented code at all.

When reports will be generated you will see them in:
- `target/cobertura.xml` and `target/scoverage.xml` files - xml reports,
- `target/site/scoverage` directory - html reports.

**Comment by gslowikowski** [comment]
@tenstriker , did you make any progress?

**Comment by tenstriker** [comment]
Oh yes, I was able to publish reports on jenkins as well. so mainly it was problem with older version of scala maven plugin as you mentioned. thank you.

**Comment by nitin2032dhir** [comment]
Hi,

i want to configure scoverage plugin with sonar using Jenkins.
How we can generate HTML reports using scoverage?
Do we need to add any entry in sonar-project.properties.
Currently, my build is generating only scoverage.xml file but to display coverage on Sonar i need Html reports. so that i can configure my Jenkins instance.

**Comment by gslowikowski** [comment]
Plugin generates html reports in `target/site/scoverage` directory. Open new issue for your problem, please.
