### ISSUE TITLE
How to invoke the plugin during 'package' or 'test' phase ? 

### ISSUE THREAD

**Issue by kiranchitturi** [scoverage/scoverage-maven-plugin#31]
Hi,

I am experimenting with the `scoverage-plugin` for the [spark-solr](https://github.com/lucidworks/spark-solr) project to get better coverage analysis of our scala code base. 

Currently our jacoco coverage reports are generated during the package phase (E.g., `mvn clean package -P coverage`) and I would like to generate the scoverage reports during the package phase too. However, I could not figure out how to invoke `scoverage` plugin during the package phase.

Is it possible to do so? Do you have any suggestions ?

The `scoverage-plugin` integration: https://github.com/lucidworks/spark-solr/blob/master/pom.xml#L115

Thanks,
Kiran.

**Comment by gslowikowski** [comment]
Hi.
Look at [this fork](https://github.com/gslowikowski/spark-solr)

**Comment by gslowikowski** [comment]
Please, use [Gitter](https://gitter.im/scoverage/scoverage-maven-plugin) or [mailing list](https://groups.google.com/forum/#!forum/scala-code-coverage-tool) for similar configuration questions.
