### ISSUE TITLE
Scala version not set doesn't fail the build

### ISSUE THREAD

**Issue by dtoms** [scoverage/scoverage-maven-plugin#32]
When running scoverage:check, I assume it will actually work.  If scala.version isn't set, it silently passes and only logs a 

WARN Scala version not set

Furthermore, minimum coverage doesn't work in this situation to fail the build either.

This is not a good behavior for a build system.  If I am running scoverage:check, I expect either coverage results, or a build failure.  Not a build success.

Please change the default behavior or add a configuration property to fail the build if scala.version is unset.

**Comment by gslowikowski** [comment]
Consider multimodule build with one or more pure Java modules. Scoverage checks only Scala classes coverage, it ignores Java classes. Scala version may not be set for Java modules and this should not fail the whole build.

**Comment by dtoms** [comment]
Thanks. That's a good point.  What is typically done with surefire/failsafe/etc is that child projects will "opt-out" by using the configuration skip property.  I can see where if you turn this into a "fail" at this point, you may break a lot of existing builds.  But if you at least enable a configuration flag to "failOnNoScala" then folks like me can enable it, and do the opt-out strategy as needed, and have safe builds.
