### ISSUE TITLE
Not getting coverage reports on classes used from another project

### ISSUE THREAD

**Issue by devshorts** [scoverage/scoverage-maven-plugin#34]
I have a multi module project that is structured kind of like:

```
/ client
   / data
/ model
   /data 
/ server
   /data
   /tests
```

Where the client and model dont 'have any tests, but are tested all via the server project.  In this scenario, scoverage shows zero coverage of any of the data classes in the client or model, even though they are used in the server.  The server shows coverage. This wildly skews my coverage report. Are there any solutions?

**Comment by gslowikowski** [comment]
What mojo(s) do you execute?

You have to run second Maven execution, e.g. `mvn scoverage:report-only` to generate reports.

When Maven runs tests on instrumented classes (while executing `scoverage:check`, `scoverage:report`, `scoverage:integration-check` or `scoverage:integration-report`), Scoverage writes information about code executed by tests in `target/scoverage-data/scoverage.measuremnts.*` files in the modules, where the code being tested (not the tests) resides.

In your case, when Scoverage executes tests in `server/tests` module, information about covered lines are written to `client/data/target/scoverage-data/scoverage.measuremnts.*` and `model/data/target/scoverage-data/scoverage.measuremnts.*` files and are not used to generate reports, because these modules were already processed by Maven before.

That's why you need second Maven run with mojos using already generated coverage data files (`mvn scoverage:report-only` or `mvn scoverage:check-only`).

**Comment by devshorts** [comment]
I see, ok that makes sense that i have to run

```
mvn scorage:report; mvn scoverage:report-only
```

And that seems to solve that issue.  However, I'm getting errors missing source roots of generated folders:

 ```
 Failed to execute goal org.scoverage:scoverage-maven-plugin:1.1.1:report-only (default-cli) on project social-sample-client: An error has occurred in SCoverage report generation: Report generation exception: No source root found for '/Users/antonkropp/src/devshorts/sample/devshorts-sample/sample-client/target/generated-sources/src/main/scala/com/devshorts/services/socialsample/data/GetsampleOutputResponse.scala' (source roots: '/Users/antonkropp/src/devshorts/sample/devshorts-sample/sample-client/src/main/scala/') -> [Help 1]
```

**Comment by gslowikowski** [comment]
You have to execute `generate-sources` before `scoverage:report-only` (or at least your mojo only, if it's possible).
Unfortunately Maven allows only one main source directory and one test source directory declared statically in the pom.xml, unlike e.g. SBT.

In your case, generating proper reports requires a lot of redundancy. I thought about creating `scoverage:test` mojo some time ago. It would only execute tests on instrumented classes without generating reports or checking minimum coverage. It would replace `scoverage:report` in your first Maven execution, to avoid first report generation (reports written by `scoverage:report` will be overwritten by `scoverage:report-only` mojo execution).

**Comment by devshorts** [comment]
I would give a big +1 to the test goal if you could make it.

Thanks for the follow up. At least for now generate sources gives me proper coverage even if it is wasteful to generate the reports twice

**Comment by devshorts** [comment]
@gslowikowski follow up question. Running:

```
mvn -U clean test scoverage:report; mvn generate-sources scoverage:report-only
```
Fails if the dependencies are not installed into the maven repo.  For example in my multi module project the scoverage:report-only fails to locate the reactor dependencies of a sibling project. I dont' want to install my snapshot local if possible. Is there a way around this?

**Comment by gslowikowski** [comment]
It shouldn't fail.

I've created very simple test project, and it works. `scoverage:report-only` does not need project dependencies resolution.
I need test project or, at least, Maven execution log (if you don't want to publish it, you can send it directly to me).

**Comment by devshorts** [comment]
In your test project do you have sibling dependencies? I..

```
/client <-- depends on config
/config
/server <-- depends on client
```

When I have this set up everything compiles and tests fine, but when I am doing the secondary 

```mvn scoverage:report-only``` 

After the `mvn clean test scoverage:report` then it can't resolve the `config` sibling dependency from `client`.  

Whats the best way to send you the maven execution log?

**Comment by gslowikowski** [comment]
Use email address from my GitHub profile.

**Comment by gslowikowski** [comment]
@devshorts I haven't received anything from you what's the status of this problem?

**Comment by pabloa** [comment]
Hi

I have the same issue with a multi module program written in Scala. It used to work when project was not multimodule.

**Comment by gslowikowski** [comment]
@pabloa prepare test project, please.

**Comment by gslowikowski** [comment]
Cannot reproduce.
