### ISSUE TITLE
1.2.0-SNAPSHOT missing files in aggregated report

### ISSUE THREAD

**Issue by ChengGit** [scoverage/scoverage-maven-plugin#35]
Hi, 

I used to use 1.1.1 against my multi module project and I wanted to get aggregated report for code coverage. However `mvn clean install socoverage-report` fails because of "connection timeout" error. I can get report in each module however i don't aggregated report.

Following your solution in another thread, I start using 1.2.0-snapshot against my project. now mvn build successfully and I can get the aggregated report. However I find the report does only cover one scala class/file in each package. In short, many files are not either tested or picked up by aggregator.

Could you have a look at this please?

Cheng

**Comment by gslowikowski** [comment]
Hi

I need more details. Having test project or at least Maven execution log with debug (with `-X` option) would help.

**Comment by gslowikowski** [comment]
Cannot reproduce.
