### ISSUE TITLE
Cannot perform check, instrumentation not performed - skipping

### ISSUE THREAD

**Issue by f9lz** [scoverage/scoverage-maven-plugin#37]
All day i am trying to debug this but with no luck..
here's my code:
https://sfgitlab.opr.test.statefarm.org/Mag-Seven/Scala-Testing-CodeCoverage

Can someone point out the mistake i am making here!!

TIA

**Comment by gslowikowski** [comment]
I cannot access your server.

**Comment by f9lz** [comment]
Below is my pom file

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>123</groupId>
  <artifactId>simpleScala</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies> 
  		<dependency> 
  			<groupId>org.apache.spark</groupId> 
  			<artifactId>spark-core_2.10</artifactId> 
  			<version>1.6.0</version> 
  		</dependency> 
  		<dependency>
  			<groupId>org.scala-lang</groupId>
  			<artifactId>scala-library</artifactId>
  			<version>2.10.5</version>
		</dependency>
		<dependency>
  			<groupId>org.scala-tools</groupId>
  			<artifactId>maven-scala-plugin</artifactId>
  			<version>2.15.2</version>
		</dependency>
		<dependency>
  			<groupId>net.alchim31.maven</groupId>
  			<artifactId>scala-maven-plugin</artifactId>
  			<version>3.2.0</version>
		</dependency>
		<dependency>
  			<groupId>org.scalacheck</groupId>
  			<artifactId>scalacheck_2.10</artifactId>
  			<version>1.13.1</version>
		</dependency>
		<dependency>
			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest_2.10</artifactId>
  			<version>2.1.7</version>
		</dependency>
		<dependency>
			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest-maven-plugin</artifactId>
  			<version>1.0</version>
		</dependency>
		 <dependency>
      		<groupId>org.scala-lang</groupId>
      		<artifactId>scala-compiler</artifactId>
     		 <version>2.10.5</version>
      	<optional>true</optional>
    	</dependency>
    	<dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-plugin_2.10</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
		<dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-runtime_2.10</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scoverage-maven-plugin</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
      		<groupId>org.scala-sbt</groupId>
      		<artifactId>test-interface</artifactId>
      		<version>1.0</version>
      		<optional>true</optional>
    	</dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>hamcrest-core</artifactId>
                    <groupId>org.hamcrest</groupId>
                </exclusion>
            </exclusions>
        </dependency>
  </dependencies> 
  
  <build>
   <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.scoverage</groupId>
          <artifactId>scoverage-maven-plugin</artifactId>
          <version>1.1.1</version>
        </plugin>
       </plugins>
    </pluginManagement>
        <plugins>
        <plugin>
  			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest-maven-plugin</artifactId>
  			<version>1.0</version>
  				<configuration>
    				<reportsDirectory>./target/scalatest-reports</reportsDirectory>
    				<junitxml>.</junitxml>
    				<filereports>WDF TestSuite.txt</filereports>
  				</configuration>
  				<executions>
    				<execution>
      					<id>test</id>
      						<goals>
       							 <goal>test</goal>
      						</goals>
    				</execution>
  				</executions>
			</plugin>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.1.1</version>
                <executions>
                    <execution>
                        <id>coverage</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludedFiles>.*Object</excludedFiles>
                    <scalaVersion>2.10.5</scalaVersion>
                    <highlighting>true</highlighting>
                </configuration>
             </plugin>
             <plugin>
             	<groupId>net.alchim31.maven</groupId>
  				<artifactId>scala-maven-plugin</artifactId>
  				<version>3.2.0</version>
             </plugin>
             <plugin>
        	<groupId>org.scala-tools</groupId>
            <artifactId>maven-scala-plugin</artifactId>
            <version>2.15.2</version>
            <executions>
            	<execution>
                	<goals>
                    	<goal>compile</goal>
                        <goal>testCompile</goal>
                     </goals>
                 </execution>
             </executions>
             <configuration>
             	<checkMultipleScalaVersions>false</checkMultipleScalaVersions>
             	<sourceDir>src/main/java</sourceDir>
             	<testSourceDir>src/test/java</testSourceDir>
                	<jvmArgs>
                    	<jvmArg>-Xms64m</jvmArg>
                        <jvmArg>-Xmx1024m</jvmArg>
                    </jvmArgs>
              </configuration>
        </plugin>
        
        </plugins>
    </build>
    
    <reporting>
    		<outputDirectory>./target/site</outputDirectory>
    		<plugins>
      <plugin>
        <groupId>org.scoverage</groupId>
        <artifactId>scoverage-maven-plugin</artifactId>
        <version>1.1.1</version>
      </plugin>
    </plugins>
  	</reporting>
  		
  
</project>

**Comment by f9lz** [comment]
My .scala file

package sf.scala

/**
 * @author f9lz
 */
object testName extends App {
  
  val p = Person("Test Run")
  
 // // $COVERAGE-OFF$
  println("Hello from " +p.name)
 // // $COVERAGE-ON$
  
}

case class Person(var name: String)

**Comment by f9lz** [comment]
my scala test case

package sf.scala
import org.scalatest.FunSuite


/**
 * @author f9lz
 */

class testNameTest extends FunSuite{
  test("the name is set correctly in the constructor"){
    val p = Person("Chicago Ohio")
    assert(p.name == "Chicago Ohio")
  }
  
  test("a persons name can be changed"){
    val p = Person("Austin Frank")
    p.name = "Huchinko"
    assert(p.name == "Huchinko")
  }
}

**Comment by f9lz** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>123</groupId>
  <artifactId>simpleScala</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies> 
  		<dependency> 
  			<groupId>org.apache.spark</groupId> 
  			<artifactId>spark-core_2.10</artifactId> 
  			<version>1.6.0</version> 
  		</dependency> 
  		<dependency>
  			<groupId>org.scala-lang</groupId>
  			<artifactId>scala-library</artifactId>
  			<version>2.10.5</version>
		</dependency>
		<dependency>
  			<groupId>org.scala-tools</groupId>
  			<artifactId>maven-scala-plugin</artifactId>
  			<version>2.15.2</version>
		</dependency>
		<dependency>
  			<groupId>net.alchim31.maven</groupId>
  			<artifactId>scala-maven-plugin</artifactId>
  			<version>3.2.0</version>
		</dependency>
		<dependency>
  			<groupId>org.scalacheck</groupId>
  			<artifactId>scalacheck_2.10</artifactId>
  			<version>1.13.1</version>
		</dependency>
		<dependency>
			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest_2.10</artifactId>
  			<version>2.1.7</version>
		</dependency>
		<dependency>
			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest-maven-plugin</artifactId>
  			<version>1.0</version>
		</dependency>
		 <dependency>
      		<groupId>org.scala-lang</groupId>
      		<artifactId>scala-compiler</artifactId>
     		 <version>2.10.5</version>
      	<optional>true</optional>
    	</dependency>
    	<dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-plugin_2.10</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
		<dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-runtime_2.10</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scoverage-maven-plugin</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
      		<groupId>org.scala-sbt</groupId>
      		<artifactId>test-interface</artifactId>
      		<version>1.0</version>
      		<optional>true</optional>
    	</dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>hamcrest-core</artifactId>
                    <groupId>org.hamcrest</groupId>
                </exclusion>
            </exclusions>
        </dependency>
  </dependencies> 
  
  <build>
   <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.scoverage</groupId>
          <artifactId>scoverage-maven-plugin</artifactId>
          <version>1.1.1</version>
        </plugin>
       </plugins>
    </pluginManagement>
        <plugins>
        <plugin>
  			<groupId>org.scalatest</groupId>
  			<artifactId>scalatest-maven-plugin</artifactId>
  			<version>1.0</version>
  				<configuration>
    				<reportsDirectory>target/scalatest-reports</reportsDirectory>
    				<junitxml>.</junitxml>
    				<filereports>WDF TestSuite.txt</filereports>
  				</configuration>
  				<executions>
    				<execution>
      					<id>test</id>
      						<goals>
       							 <goal>test</goal>
      						</goals>
    				</execution>
  				</executions>
			</plugin>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.1.1</version>
                <executions>
                    <execution>
                        <id>coverage</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludedFiles>.*Object</excludedFiles>
                    <scalaVersion>2.10.5</scalaVersion>
                    <highlighting>true</highlighting>
                </configuration>
             </plugin>
             <plugin>
             	<groupId>net.alchim31.maven</groupId>
  				<artifactId>scala-maven-plugin</artifactId>
  				<version>3.2.0</version>
             </plugin>
             <plugin>
        	<groupId>org.scala-tools</groupId>
            <artifactId>maven-scala-plugin</artifactId>
            <version>2.15.2</version>
            <executions>
            	<execution>
                	<goals>
                    	<goal>compile</goal>
                        <goal>testCompile</goal>
                     </goals>
                 </execution>
             </executions>
             <configuration>
             	<checkMultipleScalaVersions>false</checkMultipleScalaVersions>
             	<sourceDir>src/main/scala</sourceDir>
             	<testSourceDir>src/test/scala</testSourceDir>
                	<jvmArgs>
                    	<jvmArg>-Xms64m</jvmArg>
                        <jvmArg>-Xmx1024m</jvmArg>
                    </jvmArgs>
              </configuration>
        </plugin>
        
        </plugins>
    </build>
    
    <reporting>
    		<outputDirectory>target/site</outputDirectory>
    		<plugins>
      <plugin>
        <groupId>org.scoverage</groupId>
        <artifactId>scoverage-maven-plugin</artifactId>
        <version>1.1.1</version>
      </plugin>
    </plugins>
  	</reporting>
  		
  
</project>

**Comment by f9lz** [comment]
[pom.txt](https://github.com/scoverage/scoverage-maven-plugin/files/449712/pom.txt)

**Comment by gslowikowski** [comment]
Thanks, but could you create a repository in your GitHub account for this project? I don't want to create the project myself from what you provided, because I could easily reconstruct it wrongly.

**Comment by f9lz** [comment]
Thanks Thats the repository
https://github.com/f9lz/Scala-Testing-codeCoverage

**Comment by gslowikowski** [comment]
Push your project there, this repo is empty now.

**Comment by f9lz** [comment]
When i pushed my stuff, it went to the old repo that i gave in the beginning!!

**Comment by gslowikowski** [comment]
The easiest way is to checkout the GitHub repo, copy the content from the old one, without the `.git` subdirectory, commit and push.

**Comment by gslowikowski** [comment]
The elegant way is to add GitHub repo as the second remote to your local repo and push to that remote.

**Comment by f9lz** [comment]
Thanks for all the help.
This is the error i see :
 fatal: unable to access 'https://github.com/f9lz/Scala-Testing-codeCoverage.git/': Failed to connect to github.com port 443: Operation timed out

its probably with my company network settings that i cannot push the code out

**Comment by gslowikowski** [comment]
I haven't helped you yet.

**Comment by gslowikowski** [comment]
I checked your `pom.xml`. You added both `scala-maven-plugin:3.2.0` and `maven-scala-plugin:2.15.2` plugins, but executions are defined for the older one. Move executions to `scala-maven-plugin:3.2.0` and remove `maven-scala-plugin:2.15.2` (see https://github.com/scoverage/scoverage-maven-plugin/#prerequisities--limitations).
Additionally:
- you should remove all scoverage artifacts from dependencies,
- you can remove `pluginManagement` section because you have scoverage plugin defined in `plugins` section too.

Tell me if it all helps.

**Comment by f9lz** [comment]
I added every thing redundantly to see if i was missing something. i removed all of those now and still it doesnt help. Same error
[pom2.txt](https://github.com/scoverage/scoverage-maven-plugin/files/450037/pom2.txt)
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simpleScala 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:check (default-cli) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (default-cli) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ simpleScala ---
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (default-cli) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:testCompile (default) @ simpleScala ---
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Surefire report directory: /Users/f9lz/simpleScala/simpleScala/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 153 milliseconds.[0m
[36mRun starting. Expected test count is: 2[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- a persons name can be changed[0m
[36mRun completed in 282 milliseconds.[0m
[36mTotal number of tests run: 2[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:report (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ simpleScala ---
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:testCompile (default) @ simpleScala ---
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Surefire report directory: /Users/f9lz/simpleScala/simpleScala/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 166 milliseconds.[0m
[36mRun starting. Expected test count is: 2[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- a persons name can be changed[0m
[36mRun completed in 291 milliseconds.[0m
[36mTotal number of tests run: 2[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:report (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:report (coverage) @ simpleScala ---
[INFO] Skipping SCoverage report generation
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:check (default-cli) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:check (default-cli) @ simpleScala ---
[INFO] Cannot perform check, instrumentation not performed - skipping
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.131 s
[INFO] Finished at: 2016-09-01T10:12:27-05:00
[INFO] Final Memory: 20M/358M
[INFO] ------------------------------------------------------------------------

**Comment by gslowikowski** [comment]
Why I see this:
```
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ simpleScala ---
```
in the log?

**Comment by f9lz** [comment]
Because i forgot to remove it from the dependency and no i did.

**Comment by f9lz** [comment]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simpleScala 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:check (default-cli) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (default-cli) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (default-cli) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 95 milliseconds.[0m
[36mRun starting. Expected test count is: 0[0m
[32mDiscoverySuite:[0m
[36mRun completed in 218 milliseconds.[0m
[36mTotal number of tests run: 0[0m
[36mSuites: completed 1, aborted 0[0m
[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0[0m
[33mNo tests were executed.[0m
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:report (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 121 milliseconds.[0m
[36mRun starting. Expected test count is: 0[0m
[32mDiscoverySuite:[0m
[36mRun completed in 233 milliseconds.[0m
[36mTotal number of tests run: 0[0m
[36mSuites: completed 1, aborted 0[0m
[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0[0m
[33mNo tests were executed.[0m
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:report (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:report (coverage) @ simpleScala ---
[INFO] [scoverage] Generating cobertura XML report...
[INFO] [scoverage] Generating scoverage XML report...
[INFO] [scoverage] Generating scoverage HTML report...
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:check (default-cli) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:check (default-cli) @ simpleScala ---
[INFO] [scoverage] All done. Coverage was [0.00%]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.030 s
[INFO] Finished at: 2016-09-01T11:05:58-05:00
[INFO] Final Memory: 23M/348M
[INFO] ------------------------------------------------------------------------

**Comment by f9lz** [comment]
[scoverage] All done. Coverage was [0.00%]

How do i check the coverage now?

**Comment by gslowikowski** [comment]
Always execute `clean` before anything else (e.g. `mvn clean scoverage:check`) after changing plugins and configurations in `pom.xml` file.
Now all classes are compiled and `scala-maven-plugin` does nothing:
```
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
```

Additionally, I don't know why, `scalatest-maven-plugin` reports `No tests were executed`. Check this too.

**Comment by f9lz** [comment]
Thanks a ton! Coverage runs fine now

**Comment by f9lz** [comment]
I wanted to find out if we can do pit mutation testing on scala code?

**Comment by gslowikowski** [comment]
I'm closing this issue

P.S.
Remove all Maven plugins from dependencies. Probably `org.scala-sbt:test-interface` is not needed too.
