### ISSUE TITLE
Tests running multiple times

### ISSUE THREAD

**Issue by f9lz** [scoverage/scoverage-maven-plugin#39]
This is a script generated from my console and if you see, I have tests running multiple times increasing my build time. If any of you have any idea of what is happening... kindly let me know. Attaching my pom file.
[pom2.txt](https://github.com/scoverage/scoverage-maven-plugin/files/462039/pom2.txt)

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simpleScala 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ simpleScala ---
[INFO] Deleting /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simpleScala ---
[INFO] Add Source directory: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/scala
[INFO] Add Test Source directory: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/scala
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/classes
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/classes at 1473347844863
[INFO] prepare-compile in 0 s
[INFO] compile in 3 s
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/test-classes
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/scala:-1: info: compiling
[INFO] Compiling 5 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/test-classes at 1473347848992
[INFO] prepare-compile in 0 s
[INFO] compile in 4 s
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Surefire report directory: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.AnimalTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.235 sec
Running com.example.CatTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running com.example.DogTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec
Running com.example.PigTest
()Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec

Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 176 milliseconds.[0m
[36mRun starting. Expected test count is: 3[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- setting id[0m
[32m- a persons name can be changed[0m
[36mRun completed in 293 milliseconds.[0m
[36mTotal number of tests run: 3[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:check (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simpleScala ---
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-classes
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-classes at 1473347856500
[INFO] [info] Cleaning datadir [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data]
[INFO] [info] Beginning coverage instrumentation
[INFO] [info] Instrumentation completed [12 statements]
[INFO] [info] Wrote instrumentation file [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data/scoverage.coverage.xml]
[INFO] [info] Will write measurement data to [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data]
[INFO] prepare-compile in 0 s
[INFO] compile in 4 s
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Surefire report directory: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.AnimalTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.215 sec
Running com.example.CatTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running com.example.DogTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 sec
Running com.example.PigTest
()Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec

Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 144 milliseconds.[0m
[36mRun starting. Expected test count is: 3[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- setting id[0m
[32m- a persons name can be changed[0m
[36mRun completed in 266 milliseconds.[0m
[36mTotal number of tests run: 3[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:report (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simpleScala ---
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-scoverage-classes
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-scoverage-classes at 1473347863298
[INFO] [info] Cleaning datadir [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data]
[INFO] [info] Beginning coverage instrumentation
[INFO] [info] Instrumentation completed [12 statements]
[INFO] [info] Wrote instrumentation file [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data/scoverage.coverage.xml]
[INFO] [info] Will write measurement data to [/Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/scoverage-data]
[INFO] prepare-compile in 0 s
[INFO] compile in 5 s
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Surefire report directory: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.AnimalTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.236 sec
Running com.example.CatTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec
Running com.example.DogTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.058 sec
Running com.example.PigTest
()Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec

Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 158 milliseconds.[0m
[36mRun starting. Expected test count is: 3[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- setting id[0m
[32m- a persons name can be changed[0m
[36mRun completed in 283 milliseconds.[0m
[36mTotal number of tests run: 3[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:report (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:report (coverage) @ simpleScala ---
[INFO] [scoverage] Generating cobertura XML report...
[INFO] [scoverage] Generating scoverage XML report...
[INFO] [scoverage] Generating scoverage HTML report...
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:check (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:check (coverage) @ simpleScala ---
[INFO] [scoverage] All done. Coverage was [66.67%]
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:report (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simpleScala ---
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 150 milliseconds.[0m
[36mRun starting. Expected test count is: 3[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- setting id[0m
[32m- a persons name can be changed[0m
[36mRun completed in 288 milliseconds.[0m
[36mTotal number of tests run: 3[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:check (coverage) > [scoverage]test @ simpleScala >>>
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simpleScala ---
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:post-compile (coverage) @ simpleScala ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simpleScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simpleScala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simpleScala ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simpleScala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 145 milliseconds.[0m
[36mRun starting. Expected test count is: 3[0m
[32mtestNameTest:[0m
[32m- the name is set correctly in the constructor[0m
[32m- setting id[0m
[32m- a persons name can be changed[0m
[36mRun completed in 273 milliseconds.[0m
[36mTotal number of tests run: 3[0m
[36mSuites: completed 2, aborted 0[0m
[36mTests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:check (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:check (coverage) @ simpleScala ---
[INFO] [scoverage] All done. Coverage was [66.67%]
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:report (coverage) < [scoverage]test @ simpleScala <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:report (coverage) @ simpleScala ---
[INFO] [scoverage] Generating cobertura XML report...
[INFO] [scoverage] Generating scoverage XML report...
[INFO] [scoverage] Generating scoverage HTML report...
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ simpleScala ---
[INFO] Building jar: /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/simpleScala-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- pitest-maven:1.1.4:mutationCoverage (check) @ simpleScala ---
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found shared classpath plugin : Default mutation engine
10:17:54 AM PIT >> INFO : Mutating from /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/classes
10:17:55 AM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
10:17:55 AM PIT >> INFO : SLAVE : objc[21584]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be 
10:17:55 AM PIT >> INFO : SLAVE : used. Which one is undefined.

10:17:55 AM PIT >> INFO : Sending 5 test classes to slave
10:17:55 AM PIT >> INFO : Sent tests to slave
10:17:55 AM PIT >> INFO : SLAVE : 10:17:55 AM PIT >> INFO : Found  8 tests

10:17:55 AM PIT >> INFO : SLAVE : 10:17:55 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

10:17:55 AM PIT >> INFO : SLAVE : 10:17:55 AM PIT >> INFO : 8 tests received

/-\|/-\|10:17:56 AM PIT >> INFO : Calculated coverage in 1 seconds.
10:17:56 AM PIT >> INFO : Created  5 mutation test units
stderr  : objc[21585]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be stderr  : used. Which one is undefined.
stderr  : objc[21586]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be stderr  : used. Which one is undefined.
/-stderr  : objc[21587]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be stderr  : used. Which one is undefined.
\stderr  : objc[21588]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be stderr  : used. Which one is undefined.
|stderr  : objc[21589]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be stderr  : used. Which one is undefined.
/10:18:01 AM PIT >> INFO : Completed in 6 seconds
================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : 1 seconds
> build mutation tests : < 1 second
> run mutation analysis : 4 seconds
--------------------------------------------------------------------------------
> Total  : 6 seconds
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 13 mutations Killed 11 (85%)
>> Ran 18 tests (1.38 tests per mutation)
================================================================================
- Mutators
================================================================================
> org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator
>> Generated 1 Killed 0 (0%)
> KILLED 0 SURVIVED 1 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator
>> Generated 1 Killed 1 (100%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator
>> Generated 9 Killed 8 (89%)
> KILLED 8 SURVIVED 1 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.MathMutator
>> Generated 1 Killed 1 (100%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator
>> Generated 1 Killed 1 (100%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ simpleScala ---
[INFO] Installing /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/simpleScala-0.0.1-SNAPSHOT.jar to /Users/f9lz/.m2/repository/123/simpleScala/0.0.1-SNAPSHOT/simpleScala-0.0.1-SNAPSHOT.jar
[INFO] Installing /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/pom.xml to /Users/f9lz/.m2/repository/123/simpleScala/0.0.1-SNAPSHOT/simpleScala-0.0.1-SNAPSHOT.pom
[INFO] 
[INFO] --- pitest-maven:1.1.4:mutationCoverage (default-cli) @ simpleScala ---
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found shared classpath plugin : Default mutation engine
10:18:01 AM PIT >> INFO : Mutating from /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/classes
[INFO] Defaulting to group id (123*)
10:18:01 AM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
10:18:01 AM PIT >> INFO : SLAVE : objc[21590]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be 
10:18:01 AM PIT >> INFO : SLAVE : used. Which one is undefined.

10:18:01 AM PIT >> INFO : Sending 0 test classes to slave
10:18:01 AM PIT >> INFO : Sent tests to slave
10:18:02 AM PIT >> INFO : SLAVE : 10:18:02 AM PIT >> INFO : Found  0 tests

10:18:02 AM PIT >> INFO : SLAVE : 10:18:02 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

10:18:02 AM PIT >> INFO : SLAVE : 10:18:02 AM PIT >> INFO : 0 tests received

10:18:02 AM PIT >> INFO : Calculated coverage in 0 seconds.
10:18:02 AM PIT >> INFO : Created  0 mutation test units
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.312 s
[INFO] Finished at: 2016-09-08T10:18:02-05:00
[INFO] Final Memory: 44M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.4:mutationCoverage (default-cli) on project simpleScala: Execution default-cli of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by gslowikowski** [comment]
Read about `check` and `report` tasks in [documentation](https://github.com/scoverage/scoverage-maven-plugin/#how-to-use). Both execute tests.

If you want a check and a report, you should use:
- `check` and `report-only` or
- `report` and `check-only`

The first one will instrument classes, execute tests and generate coverage info. The second one will use this info.

**Comment by f9lz** [comment]
clean install -e scoverage:check scoverage:report-only org.pitest:pitest-maven:mutationCoverage

These are my arguments. Still the tests run 7 times!

**Comment by gslowikowski** [comment]
Since you execute scoverage tasks separately, don't add them to the build (I never do).

**Comment by gslowikowski** [comment]
When you execute `scoverage:check` it forks build lifecycle up to `test` phase and execute scoverage tasks bound to it in the pom. Effectively you have fork from already forked lifecycle. This is not dangerous (will not fail the build), but adds a lot of unnecessary overhead.

**Comment by f9lz** [comment]
Yes. I understand that now. Thanks.

**Comment by f9lz** [comment]
Also in my pom file i corrected report to report-only. That reduced the total tests run to only 2 times!

**Comment by gslowikowski** [comment]
Remove all scoverage tasks from `pom.xml` file.

**Comment by f9lz** [comment]
Yes! it runs only one time now. Just a "clean install" and there you go!
Thanks!
