### ISSUE TITLE
Tests run individually. but fails when i mvn-clean-install.

### ISSUE THREAD

**Issue by f9lz** [scoverage/scoverage-maven-plugin#43]
here's my pom file. 
Thanks for any thoughts 

<dependencies>

```
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-core</artifactId>
        <version>${serenity.version}</version>
    </dependency>
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-cucumber</artifactId>
        <version>${serenity.cucumber.version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.7</version>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.spark-project.akka</groupId>
        <artifactId>akka-remote_2.10</artifactId>
        <version>2.3.4-spark</version>
    </dependency>
    <dependency>
        <groupId>org.xyz.pcmod</groupId>
        <artifactId>simulation-fabrication</artifactId>
        <version>${simulation.fabrication.version}</version>
     </dependency>
     <dependency> 
        <groupId>sf.simulationExecution</groupId>
        <artifactId>simulation-execution</artifactId>
        <version>${simulation.execution.version}</version>
    </dependency> 
     <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.10</artifactId>
        <version>${spark-core.version}</version>
        <scope>provided</scope>
        <exclusions>
            <exclusion>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
            </exclusion>

        </exclusions>
   </dependency>
</dependencies>
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.18.1</version>
            <configuration>
                <!--   <skip>true</skip>-->               
               <forkCount>1</forkCount>
                <reuseForks>true</reuseForks>
                <argLine>-Xmx1024m -XX:MaxPermSize=500m</argLine>

            </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.18.1</version>
            <configuration>
                <includes>
                    <include>**/*.java</include>
                </includes>
                <argLine>-Xmx512m</argLine>
                <systemPropertyVariables>
                    <webdriver.driver>${webdriver.driver}</webdriver.driver>
                </systemPropertyVariables>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>integration-test</goal>
                        <goal>verify</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.2</version>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
            </configuration>
        </plugin>
        <plugin>
            <groupId>net.serenity-bdd.maven.plugins</groupId>
            <artifactId>serenity-maven-plugin</artifactId>
            <version>${serenity.version}</version>
            <executions>
                <execution>
                    <id>serenity-reports</id>
                    <phase>post-integration-test</phase>
                    <goals>
                        <goal>aggregate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by f9lz** [comment]
[main] ERROR net.serenitybdd.core.Serenity - 
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____  
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \ 
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/ 
          \_\                                                            

TEST FAILED WITH ERROR: Executing Simulation
---------------------------------------------------------------------
[main] ERROR net.serenitybdd.core.Serenity - TEST FAILED AT STEP When I execute
[main] ERROR net.serenitybdd.core.Serenity - 
[sparkDriver-akka.actor.default-dispatcher-3] INFO org.apache.spark.storage.BlockManagerInfo - Removed broadcast_0_piece0 on localhost:52438 in memory (size: 13.8 KB, free: 245.7 MB)
Test fails with input path not found!!??? (it sits right there.....)


[31mFailed scenarios:[0m
[31mExecution BDDs/Execution BDDs.feature:34 [0m# Scenario: Executing Simulation

1 Scenarios ([31m1 failed[0m)
6 Steps ([31m1 failed[0m, [36m1 skipped[0m, [32m4 passed[0m)
0m3.960s

org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/Users/f9lz/Local/src/simulation-bdd/target/simulation/facts/fabricated-catalog/mystuff

**Comment by gslowikowski** [comment]
Where is Scoverage in your project?

**Comment by f9lz** [comment]
This is a java project accessing scala project. So there's no scoverage in this one!

The mistake in my pom file was that... I was using "maven-failsafe-plugin" instead of "org.apache.maven.plugins" and i had to have 
                        <runOrder>reversealphabetical</runOrder> 
                        <forkCount>1</forkCount>
	                <reuseForks>true</reuseForks>
	                <argLine>-Xmx1024m -XX:MaxPermSize=500m</argLine> 
included in the <configuration>. 

i had to have the tests run in a certain order for the apache to see the input file. so i had the tests run in reverse alphabetical order. i had to have memory settings to overcome Permgen and OutOfMemory issues. I also had to have only one thread running.

This solved the errors

**Comment by gslowikowski** [comment]
This is Scoverage Maven plugin issue tracker, not Serenity Maven plugin.
