### ISSUE TITLE
Could not find goal 'test' in version 1.3.0

### ISSUE THREAD

**Issue by BloodyHell** [scoverage/scoverage-maven-plugin#48]
```
<scoverage.version>1.3.0</scoverage.version>
<scala.version>2.11.8</scala.version>
```

```
<plugin>
   <groupId>org.scoverage</groupId>
   <artifactId>scoverage-maven-plugin</artifactId>
   <version>${scoverage.version}</version>
   <configuration>
      <scalaVersion>${scala.version}</scalaVersion>
   </configuration>
</plugin>
```

After that `mvn scoverage:test` returns the following message:

> Could not find goal 'test' in plugin org.scoverage:scoverage-maven-plugin:1.1.1 among available goals check, check-only, help, integration-check, integration-report, post-compile, pre-compile, report, report-only 

When I check my local maven repo both version 1.1.1 and 1.3.0 is there.
When I execute `mvn scoverage:help` it shows the following: 

> --- scoverage-maven-plugin:1.3.0:help (default-cli) @ my-api ---
> SCoverage Maven Plugin 1.3.0
>   SCoverage Maven Plugin
> 
> This plugin has 12 goals:
> 
> ...... omitted for length reasons :) 
>
> scoverage:test
>   Executes forked scoverage life cycle up to test phase.
>   
>   In forked scoverage life cycle project is compiled with SCoverage
>   instrumentation and unit tests are executed.

Is there anything I'm missing?

**Comment by gslowikowski** [comment]
Weird. This must be some configuration problem. I need test project or at least Maven execution log with debug info ("-X" parameter).

**Comment by BloodyHell** [comment]
> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
> Maven home: /home/Dev/bin/apache-maven-3.3.9
> Java version: 1.8.0_112, vendor: Oracle Corporation
> Java home: /opt/jdk/jdk1.8.0_112/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"
> [DEBUG] Created new class realm maven.api
> [DEBUG] Importing foreign packages into class realm maven.api
> [DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
> [DEBUG]   Imported: javax.enterprise.util.* < plexus.core
> [DEBUG]   Imported: javax.inject.* < plexus.core
> [DEBUG]   Imported: org.apache.maven.* < plexus.core
> [DEBUG]   Imported: org.apache.maven.artifact < plexus.core
> [DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
> [DEBUG]   Imported: org.apache.maven.cli < plexus.core
> [DEBUG]   Imported: org.apache.maven.configuration < plexus.core
> [DEBUG]   Imported: org.apache.maven.exception < plexus.core
> [DEBUG]   Imported: org.apache.maven.execution < plexus.core
> [DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
> [DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
> [DEBUG]   Imported: org.apache.maven.model < plexus.core
> [DEBUG]   Imported: org.apache.maven.monitor < plexus.core
> [DEBUG]   Imported: org.apache.maven.plugin < plexus.core
> [DEBUG]   Imported: org.apache.maven.profiles < plexus.core
> [DEBUG]   Imported: org.apache.maven.project < plexus.core
> [DEBUG]   Imported: org.apache.maven.reporting < plexus.core
> [DEBUG]   Imported: org.apache.maven.repository < plexus.core
> [DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
> [DEBUG]   Imported: org.apache.maven.settings < plexus.core
> [DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
> [DEBUG]   Imported: org.apache.maven.usability < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
> [DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
> [DEBUG]   Imported: org.codehaus.classworlds < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
> [DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.* < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
> [DEBUG]   Imported: org.eclipse.aether.version < plexus.core
> [DEBUG]   Imported: org.slf4j.* < plexus.core
> [DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
> [DEBUG]   Imported: org.slf4j.spi.* < plexus.core
> [DEBUG] Populating class realm maven.api
> [INFO] Error stacktraces are turned on.
> [DEBUG] Reading global settings from /home/Dev/bin/apache-maven-3.3.9/conf/settings.xml
> [DEBUG] Reading user settings from /home/Dev/.m2/settings.xml
> [DEBUG] Reading global toolchains from /home/Dev/bin/apache-maven-3.3.9/conf/toolchains.xml
> [DEBUG] Reading user toolchains from /home/Dev/.m2/toolchains.xml
> [DEBUG] Using local repository at /home/Dev/.m2/repository
> [DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/Dev/.m2/repository
> [INFO] Scanning for projects...
> [DEBUG] Using mirror artifactory (https://myStore.net/artifactory/mvn) for artifactory (https://myStore.net/artifactory/mvn).
> [DEBUG] Using mirror artifactory (https://myStore.net/artifactory/mvn) for central (https://repo.maven.apache.org/maven2).
> [DEBUG] Extension realms for project my.api:apitest-scala_2.11:pom:00.00.42-SNAPSHOT: (none)
> [DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
> [DEBUG] Extension realms for project my.api:apitest-scala_2.11-core:jar:00.00.42-SNAPSHOT: (none)
> [DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
> [DEBUG] Extension realms for project my.api:apitest-scala_2.11-demo:jar:00.00.42-SNAPSHOT: (none)
> [DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] apitest-scala_2.11
> [INFO] apitest-scala_2.11-core
> [INFO] apitest-scala_2.11-demo
> [DEBUG] Resolving plugin prefix scoverage from [org.apache.maven.plugins, org.codehaus.mojo]
> [DEBUG] Resolved plugin prefix scoverage to org.scoverage:scoverage-maven-plugin from POM my.api:apitest-scala_2.11:pom:00.00.42-SNAPSHOT
> [DEBUG] === REACTOR BUILD PLAN ================================================
> [DEBUG] Project: my.api:apitest-scala_2.11:pom:00.00.42-SNAPSHOT
> [DEBUG] Tasks:   [scoverage:test]
> [DEBUG] Style:   Regular
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Project: my.api:apitest-scala_2.11-core:jar:00.00.42-SNAPSHOT
> [DEBUG] Tasks:   [scoverage:test]
> [DEBUG] Style:   Regular
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Project: my.api:apitest-scala_2.11-demo:jar:00.00.42-SNAPSHOT
> [DEBUG] Tasks:   [scoverage:test]
> [DEBUG] Style:   Regular
> [DEBUG] =======================================================================
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building apitest-scala_2.11 00.00.42-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [DEBUG] Resolving plugin prefix scoverage from [org.apache.maven.plugins, org.codehaus.mojo]
> [DEBUG] Resolved plugin prefix scoverage to org.scoverage:scoverage-maven-plugin from POM my.api:apitest-scala_2.11:pom:00.00.42-SNAPSHOT
> [DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
> [DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
> [DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
> [DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
> [DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
> [DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
> [DEBUG] === PROJECT BUILD PLAN ================================================
> [DEBUG] Project:       my.api:apitest-scala_2.11:00.00.42-SNAPSHOT
> [DEBUG] Dependencies (collect): []
> [DEBUG] Dependencies (resolve): []
> [DEBUG] Repositories (dependencies): [artifactory (https://myStore.net/artifactory/mvn, default, releases)]
> [DEBUG] Repositories (plugins)     : [artifactory (https://myStore.net/artifactory/mvn, default, releases+snapshots)]
> [DEBUG] --- init fork of my.api:apitest-scala_2.11:00.00.42-SNAPSHOT for org.scoverage:scoverage-maven-plugin:1.3.0:test (default-cli) ---
> [DEBUG] Dependencies (collect): []
> [DEBUG] Dependencies (resolve): []
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.scoverage:scoverage-maven-plugin:1.3.0:pre-compile (default-cli)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <dataDirectory default-value="${project.build.directory}/scoverage-data">${scoverage.dataDirectory}</dataDirectory>
>   <excludedFiles default-value="">${scoverage.excludedFiles}</excludedFiles>
>   <excludedPackages default-value="">${scoverage.excludedPackages}</excludedPackages>
>   <highlighting default-value="false">${scoverage.highlighting}</highlighting>
>   <localRepo>${localRepository}</localRepo>
>   <pluginArtifacts>${plugin.artifacts}</pluginArtifacts>
>   <project default-value="${project}"/>
>   <reactorProjects default-value="${reactorProjects}"/>
>   <remoteRepos>${project.remoteArtifactRepositories}</remoteRepos>
>   <scalaVersion>2.11.8</scalaVersion>
>   <scalacPluginVersion default-value="">${scoverage.scalacPluginVersion}</scalacPluginVersion>
>   <skip default-value="false">${scoverage.skip}</skip>
> </configuration>
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.scoverage:scoverage-maven-plugin:1.3.0:post-compile (default-cli)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>   <project default-value="${project}"/>
>   <skip default-value="false">${scoverage.skip}</skip>
> </configuration>
> [DEBUG] --- exit fork of my.api:apitest-scala_2.11:00.00.42-SNAPSHOT for org.scoverage:scoverage-maven-plugin:1.3.0:test (default-cli) ---
> [DEBUG] -----------------------------------------------------------------------
> [DEBUG] Goal:          org.scoverage:scoverage-maven-plugin:1.3.0:test (default-cli)
> [DEBUG] Style:         Regular
> [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
> <configuration/>
> [DEBUG] =======================================================================
> [INFO] 
> [INFO] >>> scoverage-maven-plugin:1.3.0:test (default-cli) > [scoverage]test @ apitest-scala_2.11 >>>
> [INFO] 
> [INFO] --- scoverage-maven-plugin:1.3.0:pre-compile (default-cli) @ apitest-scala_2.11 ---
> [DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=0, ConflictMarker.nodeCount=49, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=22, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=8, ConflictResolver.conflictItemCount=45, DefaultDependencyCollector.collectTime=258, DefaultDependencyCollector.transformTime=15}
> [DEBUG] org.scoverage:scoverage-maven-plugin:jar:1.3.0:
> [DEBUG]    org.scoverage:scalac-scoverage-plugin_2.10:jar:1.3.0:compile
> [DEBUG]       org.scala-lang:scala-library:jar:2.10.6:compile
> [DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
> [DEBUG]    org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
> [DEBUG]       org.apache.maven.doxia:doxia-sink-api:jar:1.0:compile
> [DEBUG]    org.apache.maven.doxia:doxia-site-renderer:jar:1.0:compile
> [DEBUG]       org.apache.maven.doxia:doxia-core:jar:1.0:compile
> [DEBUG]       org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile
> [DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-30:compile
> [DEBUG]          org.codehaus.plexus:plexus-classworlds:jar:1.2-alpha-9:compile
> [DEBUG]          junit:junit:jar:3.8.1:compile
> [DEBUG]       org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile
> [DEBUG]       org.apache.velocity:velocity:jar:1.5:compile
> [DEBUG]          commons-lang:commons-lang:jar:2.1:compile
> [DEBUG]          oro:oro:jar:2.0.8:compile
> [DEBUG]       org.apache.maven.doxia:doxia-decoration-model:jar:1.0:compile
> [DEBUG]       commons-collections:commons-collections:jar:3.2:compile
> [DEBUG]       org.apache.maven.doxia:doxia-module-apt:jar:1.0:compile
> [DEBUG]       org.apache.maven.doxia:doxia-module-fml:jar:1.0:compile
> [DEBUG]       org.apache.maven.doxia:doxia-module-xdoc:jar:1.0:compile
> [DEBUG]       org.apache.maven.doxia:doxia-module-xhtml:jar:1.0:compile
> [DEBUG] Created new class realm plugin>org.scoverage:scoverage-maven-plugin:1.3.0
> [DEBUG] Importing foreign packages into class realm plugin>org.scoverage:scoverage-maven-plugin:1.3.0
> [DEBUG]   Imported:  < maven.api
> [DEBUG] Populating class realm plugin>org.scoverage:scoverage-maven-plugin:1.3.0
> [DEBUG]   Included: org.scoverage:scoverage-maven-plugin:jar:1.3.0
> [DEBUG]   Included: org.scoverage:scalac-scoverage-plugin_2.10:jar:1.3.0
> [DEBUG]   Included: org.scala-lang:scala-library:jar:2.10.6
> [DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.24
> [DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:3.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-site-renderer:jar:1.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-core:jar:1.0
> [DEBUG]   Included: org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7
> [DEBUG]   Included: junit:junit:jar:3.8.1
> [DEBUG]   Included: org.codehaus.plexus:plexus-velocity:jar:1.1.7
> [DEBUG]   Included: org.apache.velocity:velocity:jar:1.5
> [DEBUG]   Included: commons-lang:commons-lang:jar:2.1
> [DEBUG]   Included: oro:oro:jar:2.0.8
> [DEBUG]   Included: org.apache.maven.doxia:doxia-decoration-model:jar:1.0
> [DEBUG]   Included: commons-collections:commons-collections:jar:3.2
> [DEBUG]   Included: org.apache.maven.doxia:doxia-module-apt:jar:1.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-module-fml:jar:1.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-module-xdoc:jar:1.0
> [DEBUG]   Included: org.apache.maven.doxia:doxia-module-xhtml:jar:1.0
> [DEBUG] Configuring mojo org.scoverage:scoverage-maven-plugin:1.3.0:pre-compile from plugin realm ClassRealm[plugin>org.scoverage:scoverage-maven-plugin:1.3.0, parent: sun.misc.Launcher$AppClassLoader@55f96302]
> [DEBUG] Configuring mojo 'org.scoverage:scoverage-maven-plugin:1.3.0:pre-compile' with basic configurator -->
> [DEBUG]   (f) dataDirectory = /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/target/scoverage-data
> [DEBUG]   (f) highlighting = false
> [DEBUG]   (f) localRepo =       id: local
>       url: file:///home/Dev/.m2/repository/
>    layout: default
> snapshots: [enabled => true, update => always]
>  releases: [enabled => true, update => always]
> 
> [DEBUG]   (f) pluginArtifacts = [org.scoverage:scoverage-maven-plugin:maven-plugin:1.3.0:, org.scoverage:scalac-scoverage-plugin_2.10:jar:1.3.0:compile, org.scala-lang:scala-library:jar:2.10.6:compile, org.codehaus.plexus:plexus-utils:jar:3.0.24:compile, org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile, org.apache.maven.doxia:doxia-sink-api:jar:1.0:compile, org.apache.maven.doxia:doxia-site-renderer:jar:1.0:compile, org.apache.maven.doxia:doxia-core:jar:1.0:compile, org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile, org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-30:compile, org.codehaus.plexus:plexus-classworlds:jar:1.2-alpha-9:compile, junit:junit:jar:3.8.1:compile, org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile, org.apache.velocity:velocity:jar:1.5:compile, commons-lang:commons-lang:jar:2.1:compile, oro:oro:jar:2.0.8:compile, org.apache.maven.doxia:doxia-decoration-model:jar:1.0:compile, commons-collections:commons-collections:jar:3.2:compile, org.apache.maven.doxia:doxia-module-apt:jar:1.0:compile, org.apache.maven.doxia:doxia-module-fml:jar:1.0:compile, org.apache.maven.doxia:doxia-module-xdoc:jar:1.0:compile, org.apache.maven.doxia:doxia-module-xhtml:jar:1.0:compile]
> [DEBUG]   (f) project = MavenProject: my.api:apitest-scala_2.11:00.00.42-SNAPSHOT @ /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/pom.xml
> [DEBUG]   (f) reactorProjects = [MavenProject: my.api:apitest-scala_2.11:00.00.42-SNAPSHOT @ /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/pom.xml, MavenProject: my.api:apitest-scala_2.11-core:00.00.42-SNAPSHOT @ /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/apitest-scala_2.11-core/pom.xml, MavenProject: my.api:apitest-scala_2.11-demo:00.00.42-SNAPSHOT @ /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/apitest-scala_2.11-demo/pom.xml]
> [DEBUG]   (f) remoteRepos = [      id: artifactory
>       url: https://myStore.net/artifactory/mvn
>    layout: default
> snapshots: [enabled => false, update => daily]
>  releases: [enabled => true, update => daily]
> ]
> [DEBUG]   (f) scalaVersion = 2.11.8
> [DEBUG]   (f) skip = false
> [DEBUG] -- end configuration --
> [INFO] Skipping SCoverage execution for project with packaging type 'pom'
> [INFO] 
> [INFO] --- scoverage-maven-plugin:1.3.0:post-compile (default-cli) @ apitest-scala_2.11 ---
> [DEBUG] Configuring mojo org.scoverage:scoverage-maven-plugin:1.3.0:post-compile from plugin realm ClassRealm[plugin>org.scoverage:scoverage-maven-plugin:1.3.0, parent: sun.misc.Launcher$AppClassLoader@55f96302]
> [DEBUG] Configuring mojo 'org.scoverage:scoverage-maven-plugin:1.3.0:post-compile' with basic configurator -->
> [DEBUG]   (f) project = MavenProject: my.api:apitest-scala_2.11:00.00.42-SNAPSHOT @ /home/Dev/IdeaProjects/Dev/apitest-scala_2.11/pom.xml
> [DEBUG]   (f) skip = false
> [DEBUG] -- end configuration --
> [INFO] 
> [INFO] <<< scoverage-maven-plugin:1.3.0:test (default-cli) < [scoverage]test @ apitest-scala_2.11 <<<
> [INFO] 
> [INFO] --- scoverage-maven-plugin:1.3.0:test (default-cli) @ apitest-scala_2.11 ---
> [DEBUG] Configuring mojo org.scoverage:scoverage-maven-plugin:1.3.0:test from plugin realm ClassRealm[plugin>org.scoverage:scoverage-maven-plugin:1.3.0, parent: sun.misc.Launcher$AppClassLoader@55f96302]
> [DEBUG] Configuring mojo 'org.scoverage:scoverage-maven-plugin:1.3.0:test' with basic configurator -->
> [DEBUG] -- end configuration --
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building apitest-scala_2.11-core 00.00.42-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [DEBUG] Resolving plugin prefix scoverage from [org.apache.maven.plugins, org.codehaus.mojo]
> [DEBUG] Resolved plugin prefix scoverage to org.scoverage:scoverage-maven-plugin from POM my.api:apitest-scala_2.11-core:jar:00.00.42-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] apitest-scala_2.11 ......................... SUCCESS [  0.634 s]
> [INFO] apitest-scala_2.11-core .................... FAILURE [  0.046 s]
> [INFO] apitest-scala_2.11-demo .................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.134 s
> [INFO] Finished at: 2016-12-22T10:58:19+01:00
> [INFO] Final Memory: 9M/230M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Could not find goal 'test' in plugin org.scoverage:scoverage-maven-plugin:1.1.1 among available goals check, check-only, help, integration-check, integration-report, post-compile, pre-compile, report, report-only -> [Help 1]
> org.apache.maven.plugin.MojoNotFoundException: Could not find goal 'test' in plugin org.scoverage:scoverage-maven-plugin:1.1.1 among available goals check, check-only, help, integration-check, integration-report, post-compile, pre-compile, report, report-only
> 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:290)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
> 	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor(MojoDescriptorCreator.java:238)
> 	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:206)
> 	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:127)
> 	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
> 	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
>

**Comment by gslowikowski** [comment]
Are you sure you don't override scoverage plugin version in `apitest-scala_2.11-core` module?

**Comment by BloodyHell** [comment]
Oh man.. You're totally right.
Thanks for taking the time to spot that!

I'll go sit in the corner of shame :black_joker:

**Comment by gslowikowski** [comment]
No problem.
