### ISSUE TITLE
Coverage %  is different in local and remote CI

### ISSUE THREAD

**Issue by rstiruveedula** [scoverage/scoverage-maven-plugin#59]
Hello,

Am using scoverage-maven-plugin. Code coverage is coming 20% when i ran local but getting only 4% when ran it on remote CI. Pointing to same code base in both places.

<scoverage.plugin.version>1.3.0</scoverage.plugin.version>

**Comment by gslowikowski** [comment]
Hi @rstiruveedula . Sorry for late reply.

If you still need help, reopen this issue. For sure I will need more information about your case to be able to help you.
