### ISSUE TITLE
Generate both jacoco and scoverage reports with maven

### ISSUE THREAD

**Issue by bkarunkishore** [scoverage/scoverage-maven-plugin#66]
Hi

I want to generate jacoco and scoverage reports (both) in a single build job in Jenkins. Only one of the two reports get generated. 

When I use -
`mvn -B -s $MVN_SETTINGS jacoco:prepare-agent install scoverage:report jacoco:report` 
jacoco report gets generated

Build log -
`
05:30:51 [Compile] [INFO] --- scoverage-maven-plugin:1.3.0:report (default-cli) @ ABC ---
05:30:51 [Compile] [INFO] Reading scoverage instrumentation [/workspace/Build-Pipeline/ABC/target/scoverage-data/scoverage.coverage.xml]...
05:30:51 [Compile] [INFO] Reading scoverage measurements [/workspace/Build-Pipeline/ABC/target/scoverage-data/scoverage.measurements.*]...
05:30:51 [Compile] [INFO] Generating coverage reports...
05:30:51 [Compile] [INFO] Written Cobertura XML report [/workspace/Build-Pipeline/ABC/target/cobertura.xml]
05:30:52 [Compile] [INFO] Written XML coverage report [/workspace/Build-Pipeline/ABC/target/scoverage.xml]
05:30:53 [Compile] [INFO] Written HTML coverage report [/workspace/Build-Pipeline/ABC/target/site/scoverage/index.html]
05:30:53 [Compile] [INFO] Statement coverage.: 0.00%
05:30:53 [Compile] [INFO] Branch coverage....: 0.00%
05:30:53 [Compile] [INFO] Coverage reports completed.
`

When I use - 
`mvn -B -s $MVN_SETTINGS jacoco:prepare-agent install jacoco:report scoverage:report ` 
scoverage report gets generated

Build log -
`
05:15:07 [Compile] [INFO] --- scoverage-maven-plugin:1.3.0:report (default-cli) @ ABC ---
05:15:07 [Compile] [INFO] Reading scoverage instrumentation [/workspace/Build-Pipeline/ABC/target/scoverage-data/scoverage.coverage.xml]...
05:15:07 [Compile] [INFO] Reading scoverage measurements [/workspace/Build-Pipeline/ABC/target/scoverage-data/scoverage.measurements.*]...
05:15:07 [Compile] [INFO] Generating coverage reports...
05:15:07 [Compile] [INFO] Written Cobertura XML report [/workspace/Build-Pipeline/ABC/target/cobertura.xml]
05:15:08 [Compile] [INFO] Written XML coverage report [/workspace/Build-Pipeline/ABC/target/scoverage.xml]
05:15:08 [Compile] [INFO] Written HTML coverage report [/workspace/Build-Pipeline/ABC/target/site/scoverage/index.html]
05:15:08 [Compile] [INFO] Statement coverage.: 0.00%
05:15:08 [Compile] [INFO] Branch coverage....: 0.00%
05:15:08 [Compile] [INFO] Coverage reports completed.
`

My pom file for scoverage config - 
```
Plugins section -
<plugins>
    <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.9</version>
        <configuration>
            <destFile>./target/jacoco.exec</destFile>
            <append>true</append>
        </configuration>
        <executions>
            <execution>
                <id>default-prepare-agent</id>
                <goals>
                    <goal>prepare-agent</goal>
                </goals>
            </execution>
            <execution>
                <id>default-report</id>
                <phase>prepare-package</phase>
                <goals>
                    <goal>report</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
    <plugin>
        <groupId>org.scoverage</groupId>
        <artifactId>scoverage-maven-plugin</artifactId>
        <version>1.3.0</version>
        <configuration>
            <scalaVersion>2.10.4</scalaVersion>
            <highlighting>true</highlighting>
            <aggregate>true</aggregate>
        </configuration>
    </plugin>
</plugins>

Reporting section - 
<reporting>
    <outputDirectory>${project.build.directory}/site</outputDirectory>
    <plugins>
        <plugin>
            <groupId>org.scoverage</groupId>
            <artifactId>scoverage-maven-plugin</artifactId>
            <version>1.3.0</version>
            <configuration>
                <aggregate>true</aggregate>
            </configuration>
            <reportSets>
                <reportSet>
                    <reports>
                        <report>report</report>
                    </reports>
                </reportSet>
            </reportSets>
        </plugin>
        <plugin>
        </plugins>
    </reporting>
```

Can someone please point me what is going wrong?

Many thanks

**Comment by gslowikowski** [comment]
Interesting. I will analyze your case, but for now two notes:
- you are calling `jacoco:report` twice - it's bound to Maven life cycle and added to your Maven call,
- the whole `<reporting>` section is important only if you call `site` mojo, and you don't so it's not needed here

**Comment by gslowikowski** [comment]
@bkarunkishore can you create simple test project with your configuration?

**Comment by bkarunkishore** [comment]
@gslowikowski Thank you for your response.

I have removed `jacoco:report` from maven call. It's much better now :)

I will work on project creation and update once done

**Comment by bkarunkishore** [comment]
@gslowikowski I have uploaded dummy project with my configuration

[Github project](https://github.com/bkarunkishore/scoverage-dummy-project/)

I'm invoking scoverage by - `clean scoverage:report install`

Using maven-3.3.9

**Comment by gslowikowski** [comment]
@bkarunkishore 

- your Scala classes are not compiled. You need to add and configure one of Scala compilation Maven plugins (scala-maven-plugin or sbt-compiler-maven-plugin), [here](https://github.com/scoverage/scoverage-maven-samples/tree/master/simple) are example projects

- scalatest specs are not automatically recognized as tests by Surefire plugin, look [here](https://github.com/play2-maven-plugin/play2-maven-test-projects/blob/master/play27/scala/starter-example/test/UnitSpec.scala#L14) how to make it work, or [here](https://github.com/scoverage/scoverage-maven-samples/tree/master/different-test-frameworks/scalatest) how to use ScalaTest Maven plugin to run them
