### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by gslowikowski** [scoverage/scoverage-maven-plugin#70]

**Comment by jqno** [comment]
I noticed there have been releases for Scala 2.13 for other SCoverage subprojects. Is there a roadmap for this one?

**Comment by cosminci** [comment]
Is anyone still looking at this? It's a blocker for any Scala Maven projects with SCoverage upgrading to Scala 2.13.

**Comment by gslowikowski** [comment]
Hi. I will take care of this soon.

**Comment by jozic** [comment]
@gslowikowski do you need any help on moving forward here?
Thanks to @jqno we already have a PR #73, but just in case you need some other help, I'm willing to help to push this
Thank you!

**Comment by gslowikowski** [comment]
Snapshot `1.4.0-SNAPSHOT` deployed to [Sonatype OSS Snapshots](https://oss.sonatype.org/content/repositories/snapshots/) repository.

**Comment by hveiga** [comment]
Hi, I am trying to update my maven project to Scala 2.13 but I must be doing something wrong since I am getting the following error while trying to `mvn package`:

```
[INFO] --- scoverage-maven-plugin:1.4.0-RC1:pre-compile (scoverage) @ mylib_2.13 ---
[WARNING] The POM for org.scala-lang:scala-library:jar:2.12.8 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.400 s
[INFO] Finished at: 2019-10-05T14:34:05-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scoverage:scoverage-maven-plugin:1.4.0-RC1:pre-compile (scoverage) on project mylib_2.13: Execution scoverage of goal org.scoverage:scoverage-maven-plugin:1.4.0-RC1:pre-compile failed: Plugin org.scoverage:scoverage-maven-plugin:1.4.0-RC1 or one of its dependencies could not be resolved: Failure to find org.scala-lang:scala-library:jar:2.12.8 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
It seems to be looking for 2.12.8 while I have the project configured to use 2.13.1. Any pointers on how to solve this issue?
