### ISSUE TITLE
Build fail when instrumenting the spark source code with scoverage plugin

### ISSUE THREAD

**Issue by ramanmishra** [scoverage/scoverage-maven-plugin#76]
Steps to reproduce the error.
1. Clone the spark repo from git.
change all the pom.xml parents as well as the submodules
<artifactId>spark-parent_2.11</artifactId>
  <version>2.4.4-SNAPSHOT</version>

2. change the build command in dev/make-distribution.sh
BUILD_COMMAND=("$MVN" -T 1C -DskipTests clean scoverage:package -e $@)

3. Try building the code I am getting the following error.
 Could not resolve dependencies for project org.apache.spark:spark-tags_2.11:pom:2.4.4-SNAPSHOT: Failure to find org.apache.spark:spark-multi-tenant-history-server_2.11:jar:2.4.4-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced

changes for scoverage enablement.
<plugin>
        <groupId>org.scoverage</groupId>
        <artifactId>scoverage-maven-plugin</artifactId>
        <version>1.4.0-RC1</version>
        <configuration>
		<highlighting>true</highlighting>
                <minimumCoverage>0</minimumCoverage>
                <failOnMinimumCoverage>true</failOnMinimumCoverage>
            </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>report</goal> 
                </goals>
            </execution>
        </executions>
     </plugin>

<reporting>
        <plugins>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.4.0-RC1</version>
                <reportSets>
                    <reportSet>
                            <reports>
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
  </reporting>

**Comment by jozic** [comment]
Please ask in spark repo/community if this is still relevant. Doesn't look like the error you had is related to scoverage plugin. Please comment/reopen if you still think it's related. Thanks
