### ISSUE TITLE
any possible to load css  or js offline in report

### ISSUE THREAD

**Issue by yuxh** [scoverage/scoverage-maven-plugin#78]
Every time it takes some time to download css and js in report(my network is not very desirable),  any possible way to switch to offline mode?

**Comment by jozic** [comment]
Hey @yuxh 
I believe that was addressed in the main component by https://github.com/scoverage/scalac-scoverage-plugin/pull/236. 
Please try one of the latest versions to check if the issue is gone.
Please reopen with more details if you still have issues.
