### ISSUE TITLE
java.lang.NoClassDefFoundError scoverage/Invoker$ in scoverage-maven-plugin 1.4.0

### ISSUE THREAD

**Issue by shakya-manish** [scoverage/scoverage-maven-plugin#85]
I am using scoverage 1.4.0 in my maven project, But i am getting run time error "java.lang.NoClassDefFoundError scoverage/Invoker$"

**Comment by jozic** [comment]
@shakya-manish do you still have the issue? If so, can you please share more details? ideally a sample project that reproduces the issue

**Comment by jozic** [comment]
Please reopen if this is still valid
