### ISSUE TITLE
how to exclude the java package for AOP with Aspect J 

### ISSUE THREAD

**Issue by chp008** [scoverage/scoverage-maven-plugin#86]
issue 1: 
Project Package
   java 
      com.aspects
       -- log.java
   scala
       -- function.scala

i want to exclude the java package for unit test coverage, then i change my pom.xml 
<groupId>org.scoverage</groupId>
<artifactId>scoverage-maven-plugin</artifactId>
<version>${scoverage.plugin.version}</version>
<configuration>
    <minimumCoverage>80</minimumCoverage>
    <failOnMinimumCoverage>false</failOnMinimumCoverage>
    <excludedPackages>(empty);com\.aspects\.*</excludedPackages>
    <excludedFiles>com\.aspects\.log*</excludedFiles>
</configuration>

it does not work. 

issue 2: 
i make a workaround for it.  i write the unit test for log.java.  i can see the unit test is execution.  but the sonar report still saying the coverage is zero for log.java

**Comment by jozic** [comment]
Hi @chp008 
this plugin instruments only Scala code and thus it can't get coverage from Java code. You probably need to collect coverage for Scala and Java separately. Not sure if Sonar can combine those for you.
