### ISSUE TITLE
Generate for specific classes only?

### ISSUE THREAD

**Issue by sjain94** [scoverage/scoverage-maven-plugin#90]
Is it possible to generate the report for specific classes only?

I eventually want to integrate this with `Gitlab`, so that in a `Merge Request`, we can compare the test coverage of source and target branch for the changed classes only.

**Comment by jozic** [comment]
Hi @sjain94ou
please read docs for https://github.com/scoverage/scalac-scoverage-plugin
I don't think it's possible to collect coverage for specific files, but you can probably achieve this by excluding all the other files except the ones you need.
