### ISSUE TITLE
Fail on java 8 mix scala2.11 project

### ISSUE THREAD

**Issue by shadowinlife** [scoverage/scoverage-maven-plugin#91]
Failed to execute goal org.scoverage:scoverage-maven-plugin:1.4.1:report (default-cli) on project dla-spark-repl: An error has occurred in SCoverage report generation: Report generation exception: No source root found for '/xxx/dla-spark-plugins/dla-spark-repl/src/main/scala/com/aliyun/dla/repl/package.scala' (source roots: '/xxx/dla-spark-plugins/dla-spark-repl/src/main/java/') -> [Help 1]

In the project, there is java source directory and scala source directory. But it seems that scoverage can't find the right way
```xml
 <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.4.1</version>
                <configuration>
                    <scalaVersion>2.11.12</scalaVersion>
                    <aggregate>true</aggregate>
                </configuration>
            </plugin>
```

**Comment by Quentame** [comment]
Hi @shadowinlife !

How did you solve the issue ?

I am getting almost the same issue:

```shell
[ERROR] Failed to execute goal org.scoverage:scoverage-maven-plugin:1.4.1.:report (default-cli) on project core: An error has occurred in SCoverage report generation: Report generation exception: No source root found for 'C:\XXX\project-src\core\src\test\scala\com\XXX\XXX\configuration\ElasticSearchConfTest.scala' (source roots: 'C:\XXX\project-src\core\src\main\scala\') -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.scoverage:scoverage-maven-plugin:1.4.1:report (default-cli) on project core: An error has occurred in SCoverage report generation: Report generation exception 
```

Versions:
lib: 1.4.1
Java: 8
Scala: 2.11

Thanks !

**Comment by steinhae** [comment]
This solved it for me.
https://github.com/scoverage/scoverage-maven-plugin/issues/38#issuecomment-245629081

**Comment by shadowinlife** [comment]
I

> 

Hi, sorry for reply this message so late

I have not resolved this issue, but changed to sbt and it seems that sbt can find right root source when use java mix scala source folder
