### ISSUE TITLE
Consider using Scala's patch version to determine the artifactId of the scalac-scoverage-plugin

### ISSUE THREAD

**Issue by stewartHutchins** [scoverage/scoverage-maven-plugin#94]
Hi,

We are currently trying to use the `check` goal with the scoverage-maven-plugin version: 1.4.1 and Scala version 2.12.13

When configuring scalacPluginVersions with value: `1.4.1` or `1.4.2` we get the following error:
`java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/report`

When using scalacPluginVersions: `1.4.3` or greater we get an error similar to the following:
`Could not find artifact org.scoverage:scalac-scoverage-plugin-2.12:jar:1.4.7 in <internal-repository>`); this is during the `pre-compile stage`

Based on this [sbt-scoverage issue](https://github.com/scoverage/sbt-scoverage/issues/319) we gather that the Scala 2.12.13 compiler not backwards compatible (resulting in the 1st error). I'm assuming this is why the scala-scoverage-plugin has begun to include Scala's patch version as part of it's artifactId.
Additionally, based on [SCoveragePreCompileMojo](https://github.com/scoverage/scoverage-maven-plugin/blob/master/src/main/java/org/scoverage/plugin/SCoveragePreCompileMojo.java#L250) we gather that the plugin ignores Scala's patch version when determining which version of the scalac-scoverage-plugin to use (resulting in the 2nd error).

If the above seems correct and reasonable, would you consider updating the maven plugin so that we are able to use a newer version of the scalac-scoverage-plugin - allowing us to use SCoverage with Scala 2.12.13?

Please let me know if the provided information is not sufficient.

Thanks,
Stewart

**Comment by vu1999** [comment]
i have the same problem (error 1) :(( waiting for new version for maven

**Comment by chetanmeh** [comment]
Raised PR #95 to follow above suggestion

**Comment by gslowikowski** [comment]
Version `1.4.11` addressing this issue was released today (version number aligned with the latest version of `scalac-scoverage-plugin`).
