### ISSUE TITLE
Odd requirement for scala source routes to be registered as java routes

### ISSUE THREAD

**Issue by IanMartin24601** [scoverage/scoverage-maven-plugin#97]
Hi,

This would be a really useful plugin, but I cant find a way to tell it where the scala source routes are - it appears that it is loading the java source routes.
In simpler projects, these can both just be set to the same thing, but when using other plugins that make the (fair) assumption that all the registered java source routes are for java code, this option becomes unworkable.
Would it be possible to get an override config option to allow the specifying of a list of relative source routes?

Thanks in advance.

**Comment by jozic** [comment]
Hey @IanMartin24601, not sure it's still relevant, but if so, could you please provide more details? ideally a small project to reproduce the issue or at least the pom you have issues with and your sources layout. Thanks

**Comment by jozic** [comment]
Please reopen with more details if the issue is still relevant
