### ISSUE TITLE
addScalacArgs option breaks scoverage

### ISSUE THREAD

**Issue by ashokaupadhya** [scoverage/scoverage-maven-plugin#99]
I have following configuration for scala maven plugin. Adding "addScalacArgs" doesn't generate coverage info. I see "Skipping SCoverage report generation" in the log but if i remove "addScalacArgs" reports are generated. 

scala version 2.11.12

```
<plugin>
   <groupId>net.alchim31.maven</groupId>
   <artifactId>scala-maven-plugin</artifactId>
   <version>4.5.4</version>
   <executions>
      <execution>
         <id>scala-compile-first</id>
         <phase>process-resources</phase>
         <goals>
            <goal>add-source</goal>
            <goal>compile</goal>
         </goals>
      </execution>
      <execution>
         <id>scala-test-compile</id>
         <phase>process-test-resources</phase>
         <goals>
            <goal>testCompile</goal>
         </goals>
      </execution>
   </executions>
   <configuration>
      <addScalacArgs>-target:jvm-1.8</addScalacArgs>
      <scalaVersion>${scala-version}</scalaVersion>
      <javacGenerateDebugSymbols>true</javacGenerateDebugSymbols>
   </configuration>
</plugin>
```

**Comment by vivekaradshan** [comment]
Any updates on this? We are facing the same issue addScalacArgs is skipping scoverage generation

**Comment by vivekaradshan** [comment]
Try using the below. It resolved the issue
<configuration>
  <args>
    <arg>-target:jvm-1.8</arg>
  </args>
</configuration>

**Comment by vivekaradshan** [comment]
I tried passing in the below format. It resolved the issue
`          <configuration>
            <args>
              <arg>-target:jvm-1.8</arg>
            </args>
          </configuration>`

**Comment by jozic** [comment]
README specifies this limitation [here](https://github.com/scoverage/scoverage-maven-plugin#prerequisities--limitations)
Also, `scala-maven-plugin` doc also [states](https://davidb.github.io/scala-maven-plugin/compile-mojo.html#addScalacArgs) that `addScalacArg`can't be used from pom.
Please send a PR if you think the doc can be improved. Thanks.
